name: 'XRPL Hooks Analyzer'
description: 'Analyze XRPL hook deploy fee, execution fee'
inputs:
  inPath:
    description: 'directory of c files'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install XRPLD Netgen
      shell: bash
      run: |
        pip install xrpld-netgen
    - name: Run XRPLD
      shell: bash
      run: |
        npm run xrpld:start
    - name: Run Analyzer
      shell: bash
      run: |
        node dist/index.js
      env:
        IN_PATH: ${{ inputs.inPath }}

